// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: drawtext/drawtext.proto

package drawtext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DrawRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src            string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Text           string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Index          int64  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	FontScale      int64  `protobuf:"varint,4,opt,name=fontScale,proto3" json:"fontScale,omitempty"`
	FontColor      string `protobuf:"bytes,5,opt,name=fontColor,proto3" json:"fontColor,omitempty"`
	OutlineColor   string `protobuf:"bytes,6,opt,name=outlineColor,proto3" json:"outlineColor,omitempty"`
	OutlineScale   int64  `protobuf:"varint,7,opt,name=outlineScale,proto3" json:"outlineScale,omitempty"`
	DisableOutline bool   `protobuf:"varint,8,opt,name=disableOutline,proto3" json:"disableOutline,omitempty"`
	Distort        bool   `protobuf:"varint,9,opt,name=distort,proto3" json:"distort,omitempty"`
}

func (x *DrawRequest) Reset() {
	*x = DrawRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drawtext_drawtext_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawRequest) ProtoMessage() {}

func (x *DrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drawtext_drawtext_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawRequest.ProtoReflect.Descriptor instead.
func (*DrawRequest) Descriptor() ([]byte, []int) {
	return file_drawtext_drawtext_proto_rawDescGZIP(), []int{0}
}

func (x *DrawRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *DrawRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DrawRequest) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DrawRequest) GetFontScale() int64 {
	if x != nil {
		return x.FontScale
	}
	return 0
}

func (x *DrawRequest) GetFontColor() string {
	if x != nil {
		return x.FontColor
	}
	return ""
}

func (x *DrawRequest) GetOutlineColor() string {
	if x != nil {
		return x.OutlineColor
	}
	return ""
}

func (x *DrawRequest) GetOutlineScale() int64 {
	if x != nil {
		return x.OutlineScale
	}
	return 0
}

func (x *DrawRequest) GetDisableOutline() bool {
	if x != nil {
		return x.DisableOutline
	}
	return false
}

func (x *DrawRequest) GetDistort() bool {
	if x != nil {
		return x.Distort
	}
	return false
}

type DrawReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DrawReply) Reset() {
	*x = DrawReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drawtext_drawtext_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrawReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawReply) ProtoMessage() {}

func (x *DrawReply) ProtoReflect() protoreflect.Message {
	mi := &file_drawtext_drawtext_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawReply.ProtoReflect.Descriptor instead.
func (*DrawReply) Descriptor() ([]byte, []int) {
	return file_drawtext_drawtext_proto_rawDescGZIP(), []int{1}
}

func (x *DrawReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TextReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filenames string `protobuf:"bytes,1,opt,name=filenames,proto3" json:"filenames,omitempty"`
}

func (x *TextReply) Reset() {
	*x = TextReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drawtext_drawtext_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextReply) ProtoMessage() {}

func (x *TextReply) ProtoReflect() protoreflect.Message {
	mi := &file_drawtext_drawtext_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextReply.ProtoReflect.Descriptor instead.
func (*TextReply) Descriptor() ([]byte, []int) {
	return file_drawtext_drawtext_proto_rawDescGZIP(), []int{2}
}

func (x *TextReply) GetFilenames() string {
	if x != nil {
		return x.Filenames
	}
	return ""
}

var File_drawtext_drawtext_proto protoreflect.FileDescriptor

var file_drawtext_drawtext_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x72, 0x61, 0x77, 0x74, 0x65, 0x78, 0x74, 0x2f, 0x64, 0x72, 0x61, 0x77, 0x74,
	0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x02, 0x0a, 0x0b, 0x44, 0x72, 0x61, 0x77, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f, 0x6e, 0x74, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x66, 0x6f, 0x6e, 0x74, 0x53, 0x63, 0x61, 0x6c, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x22,
	0x0a, 0x0c, 0x6f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x63, 0x61,
	0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6f, 0x75, 0x74, 0x6c, 0x69, 0x6e,
	0x65, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e,
	0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x64, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x74, 0x22, 0x1f, 0x0a, 0x09, 0x44, 0x72, 0x61, 0x77,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x09, 0x54, 0x65, 0x78,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x32, 0x64, 0x0a, 0x08, 0x44, 0x72, 0x61, 0x77, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x22, 0x0a, 0x04, 0x44, 0x72, 0x61, 0x77, 0x12, 0x0c, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0a, 0x2e, 0x54,
	0x65, 0x78, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x64, 0x65, 0x2d, 0x64, 0x75,
	0x63, 0x6b, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x6f, 0x6d, 0x65, 0x6d, 0x65, 0x73, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x64, 0x72, 0x61, 0x77, 0x74, 0x65, 0x78, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_drawtext_drawtext_proto_rawDescOnce sync.Once
	file_drawtext_drawtext_proto_rawDescData = file_drawtext_drawtext_proto_rawDesc
)

func file_drawtext_drawtext_proto_rawDescGZIP() []byte {
	file_drawtext_drawtext_proto_rawDescOnce.Do(func() {
		file_drawtext_drawtext_proto_rawDescData = protoimpl.X.CompressGZIP(file_drawtext_drawtext_proto_rawDescData)
	})
	return file_drawtext_drawtext_proto_rawDescData
}

var file_drawtext_drawtext_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_drawtext_drawtext_proto_goTypes = []interface{}{
	(*DrawRequest)(nil),   // 0: DrawRequest
	(*DrawReply)(nil),     // 1: DrawReply
	(*TextReply)(nil),     // 2: TextReply
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_drawtext_drawtext_proto_depIdxs = []int32{
	0, // 0: DrawText.Draw:input_type -> DrawRequest
	3, // 1: DrawText.GetFontNames:input_type -> google.protobuf.Empty
	1, // 2: DrawText.Draw:output_type -> DrawReply
	2, // 3: DrawText.GetFontNames:output_type -> TextReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_drawtext_drawtext_proto_init() }
func file_drawtext_drawtext_proto_init() {
	if File_drawtext_drawtext_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drawtext_drawtext_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrawRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drawtext_drawtext_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrawReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drawtext_drawtext_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drawtext_drawtext_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drawtext_drawtext_proto_goTypes,
		DependencyIndexes: file_drawtext_drawtext_proto_depIdxs,
		MessageInfos:      file_drawtext_drawtext_proto_msgTypes,
	}.Build()
	File_drawtext_drawtext_proto = out.File
	file_drawtext_drawtext_proto_rawDesc = nil
	file_drawtext_drawtext_proto_goTypes = nil
	file_drawtext_drawtext_proto_depIdxs = nil
}
